# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifdef MAIN

# Main section

URVERSION = $(shell urweb -version)
.PHONY: all
all: ./lib.urp ./test/Test1.exe ./test/Test2.exe ./test/Test3.exe ./test/Test4.exe
.PHONY: clean
clean: 
	rm -rf .cake3 ./test/Test1.exe ./test/Test2.exe ./test/Test3.exe ./test/Test4.exe
.PHONY: run
run: ./test/Test4.exe
	./test/Test4.exe
./test/Test4.exe: ./test/Test4.urp $(call GUARD,URVERSION)
	urweb -dbms sqlite ./test/Test4
./test/Test4.urp: ./test/Test4.urp.in
	cat ./test/Test4.urp.in > ./test/Test4.urp
./test/Test4.urp.in: ./lib.urp ./test/Test4.ur
	touch ./test/Test4.urp.in
./test/Test3.exe: ./test/Test3.urp $(call GUARD,URVERSION)
	urweb -dbms sqlite ./test/Test3
./test/Test3.urp: ./test/Test3.urp.in
	cat ./test/Test3.urp.in > ./test/Test3.urp
./test/Test3.urp.in: ./lib.urp ./test/Test3.ur
	touch ./test/Test3.urp.in
./test/Test2.exe: ./test/Test2.urp $(call GUARD,URVERSION)
	urweb -dbms sqlite ./test/Test2
./test/Test2.urp: ./test/Test2.urp.in
	cat ./test/Test2.urp.in > ./test/Test2.urp
./test/Test2.urp.in: ./lib.urp ./test/Test2.ur
	touch ./test/Test2.urp.in
./test/Test1.exe: ./test/Test1.urp $(call GUARD,URVERSION)
	urweb -dbms sqlite ./test/Test1
./test/Test1.urp: ./test/Test1.urp.in
	cat ./test/Test1.urp.in > ./test/Test1.urp
./test/Test1.urp.in: ./lib.urp ./test/Test1.ur
	touch ./test/Test1.urp.in
./lib.urp: ./lib.urp.in
	cat ./lib.urp.in > ./lib.urp
./lib.urp.in: ./state.ur ./state.urs
	touch ./lib.urp.in
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@

else

# Prebuild/postbuild section

.PHONY: all
all: .fix-multy1
.PHONY: clean
clean: .fix-multy1
.PHONY: run
run: .fix-multy1
.PHONY: ./test/Test4.exe
./test/Test4.exe: .fix-multy1
.PHONY: ./test/Test4.urp
./test/Test4.urp: .fix-multy1
.PHONY: ./test/Test4.urp.in
./test/Test4.urp.in: .fix-multy1
.PHONY: ./test/Test3.exe
./test/Test3.exe: .fix-multy1
.PHONY: ./test/Test3.urp
./test/Test3.urp: .fix-multy1
.PHONY: ./test/Test3.urp.in
./test/Test3.urp.in: .fix-multy1
.PHONY: ./test/Test2.exe
./test/Test2.exe: .fix-multy1
.PHONY: ./test/Test2.urp
./test/Test2.urp: .fix-multy1
.PHONY: ./test/Test2.urp.in
./test/Test2.urp.in: .fix-multy1
.PHONY: ./test/Test1.exe
./test/Test1.exe: .fix-multy1
.PHONY: ./test/Test1.urp
./test/Test1.urp: .fix-multy1
.PHONY: ./test/Test1.urp.in
./test/Test1.urp.in: .fix-multy1
.PHONY: ./lib.urp
./lib.urp: .fix-multy1
.PHONY: ./lib.urp.in
./lib.urp.in: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./Makefile MAIN=1 $(MAKECMDGOALS)

endif
